### ISSUE TITLE
Error: Gain out of range

### ISSUE THREAD

**Issue by mehdideveloper** [xmikos/soapy_power#1]
Hi
I'm testing soapy_power on Mac OS X (I'm using the latest version of soapy_power)
When I run it (with or without arguments, with or without any SDRs plugged-in), I get this error:

> WARNING: Sample rate 2000000.0 Hz is not supported, setting it to 96000.0 Hz!
Traceback (most recent call last):
  File "/usr/local/bin/soapy_power", line 11, in <module>
    load_entry_point('soapy-power==1.1.0', 'console_scripts', 'soapy_power')()
  File "/usr/local/lib/python3.6/site-packages/soapy_power-1.1.0-py3.6.egg/soapypower/__main__.py", line 225, in main
  File "/usr/local/lib/python3.6/site-packages/soapy_power-1.1.0-py3.6.egg/soapypower/power.py", line 24, in __init__
  File "/usr/local/lib/python3.6/site-packages/SimpleSoapy-1.1.0-py3.6.egg/simplesoapy.py", line 59, in __init__
  File "/usr/local/lib/python3.6/site-packages/SimpleSoapy-1.1.0-py3.6.egg/simplesoapy.py", line 166, in gain
ValueError: Gain out of range (0.0, 0.0)!

My Python version: 3.6.0
OS : OS X 10.12.2
SoapySDR API and ABI version: 0.6.0

Any ideas?

**Comment by xmikos** [comment]
If you run it without parameters, it tries to do default sweep. Without connected SDR it should print exception, but with connected SDR (which is supported by SoapySDR) it should work.

Try to run `soapy_power --detect` to see if it detects your devices right and than specify correct device with `-d driver=hackrf` (or similar) option.

**Comment by xmikos** [comment]
Btw. that error looks like it found (and tried to use) some SDR with 96 kHz max. sample rate.

**Comment by mehdideveloper** [comment]
Thanks.

**Comment by xmikos** [comment]
Did you resolved it? Now it works?

**Comment by mehdideveloper** [comment]
@xmikos Yes, thank you.
I wasn't using the "-d driver" argument before.
My original problem is solved, now I'm seeing lots of 

> "WARNING: readStream returned only 65520 samples, but buffer size is 65536!"


in the output. I'm investigating it to see whether it's my fault or should I report it as an issue.

**Comment by xmikos** [comment]
This can be problem with SoapySDR driver, what SDR are you using?

**Comment by mehdideveloper** [comment]
I'm using SDRPlay RSP2.
It's working without problem with CubicSDR (which is using Soapy* backend)

Here's my arguments:
`soapy_power -r 2M -f 88M:98M -B 100k -F rtl_power -t 10 -d driver=sdrplay`

**Comment by xmikos** [comment]
I have SDRplay RSP too, but couldn't get it to work with latest libsdrplay on Arch Linux (not even in CubicSDR), it gives me some USB errors. I am going to look into it, but it will take some time.
