### ISSUE TITLE
Could you please check -R option is working as expected ?

### ISSUE THREAD

**Issue by mariocannistra** [xmikos/soapy_power#3]
Could you please check the -R option to remove the DC spike in the middle of the FFT ? 
Plotting the data that I'm collecting during scans I can still see that, despite I have specified the -R option.
These are my command parameters:

`-r 15M -f 15M:30M -b 2000 -G "LNA=45,TIA=15,PGA=0" -w 30M -t 0.1 -e 900 -R --reset-stream`

See an example scan plotted here:
https://cloud.githubusercontent.com/assets/1177953/25754297/fb553cee-31be-11e7-9dd3-8dbbd4369a01.png

**Comment by xmikos** [comment]
It has definitely worked in my tests. But it simply removes FFT bin in DC and interpolates it from closest bins. Maybe --detrend constant could be better option for you?

**Comment by mariocannistra** [comment]
Thank you.
I tried 
`--detrend constant`
and seen it's removed, but leaves a darker line (lower value in the output compared to bins on both sides):
![utc20170507115743-mcrao-hf-15 000m-30 000m-b2000-t0 5-glna45tia15pga0-e3m](https://cloud.githubusercontent.com/assets/1177953/25780846/509ce5f0-332f-11e7-8772-fae9ae084c47.png)

I also tested using
`--fft-window boxcar -R`
and seems to work better, at least for my use case:
![utc20170507102612-mcrao-hf-15 000m-30 000m-b2000-t0 5-glna45tia15pga0-e30m](https://cloud.githubusercontent.com/assets/1177953/25780796/79880e96-332e-11e7-9f83-17f7b229ca72.png)

I will do more tests when possible since at the moment I'm not sure about the advantages of using different window types.
closing the issue / question... 
Cheers,
mario
