### ISSUE TITLE
include recording settings in binary format

### ISSUE THREAD

**Issue by xloem** [xmikos/soapy_power#6]
It would be great if the binary format included a header specifying the window choice, device settings, etc, to keep a log of all data regarding the recording.

**Comment by xloem** [comment]
Resolving this issue would ideally involve:
- writing out all data needed to reproduce the recording environment exactly, including a representation for all configuration options passed on the command line, all the SoapySDR settings, and details on what device is selected to record from (ideally some device-specific string that might include a serial number, but even just the model is good)
- updating both the reading and writing code to support the new format
- maintaining compatibility with the old format, by for example changing the magic string when writing in the new format, and including reading code for both the old and new format based on the magic string
- testing the code to verify it reads out what was written correctly

If someone does not own a usb radio, I would be happy to give you an RTL-SDR to test with.

**Comment by alexnask** [comment]
Hi, I'm interested on working on this feature.  
Do you think using a simulated device is fine?  
I've found [this](https://github.com/osqzss/LimeGPS) projects which looks like it would get the job done.
